apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: poc-frontend
  namespace: flux-system
spec:
  releaseName: poc-frontend
  targetNamespace: default
  chart:
    spec:
      chart: ./chart
      sourceRef:
        kind: GitRepository
        name: platform-lab-frontend
        namespace: flux-system
  interval: 1h0m0s
  values:
    component:
      serviceAccount: poc-frontend
      apiBaseUrl: http://platform-lab-api
      vault:
        role: poc-frontend
        authSecret: poc/network/api