apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: azure-keyvault
  namespace: default
spec:
  encryptedData:
    azurekeyvault.hcl: AgBNWNYeG6Lp5Lxpa9vAReXlyg4XqJF1DyMWZaIsGeiOJwLHgjuAXmJVp7tuTtl1Zcn0ARUN8XxuxsXaFVbinT4NZA5Oup/4mvUAsmflomTSxLPo0dh1NtvqOLbXfRmNei+QBcssah/HJolyIYkTlzeIU+UhO1keuBN+fZ/DII9ZwYdODKnVuVarddEeS4R3MRrKg58r9S9Cj+erJ2WIapsBjwTmxL9K+yp9G94J1UeUjs2PwSKoCOMAUeo16isI1I7MP0hlAkbe8X3r+CrHDADCKUkZtv5XvJXp4PqKFdvL/2eSzyYiDm5klvvS5UyNVq7+IdC4pdjH2+EX0k1jMt5RwyOEev78ERzFoh6WSETSj1gsWNu31POjBCis0oGJQvtHZTGQeJa0LmW7b8DHhzMPutHJLot435utbc0ab2oD5ZxSCGTuGnYV9fMRSd89MCuQ9/huwnf/VKTG0aIyiEin0zrzE/v94i7obvtZIjFPpYQr/ApGkplxtsVZmDnqFvcrxS3x8XUyEme/5NuDU16mLxsQltYT2FIF/TEyh3+38zW888v6/xhNKGPZ5COSSWDmOK03GI6nQ5+JvJGfgMyH+TlS2KkgADLrQ6UBtHbYi/O8FX6K0z2AJUAgobVoYI8fTgLVKKJ9ZxbtMEaaX3pUZuzuVmCgWfOvoJZ7tSUifIbibTlIMEPjw6znRyrXBmpqSKwiQ9GcGZt9CgwIMgBKgnySBG41a6OKHwtJySH3KOaURHjATaLSxuDbADjwjlJoh4Gsg5EvuoP2WrXtoMgpfFKXvFpKm0L5C3OfgZ0GDJoLmQFzPZvgMQKiWX/CiAaqpX19Po5irAFe+CXvBIN4//Z1gIQWKavr+JC+bUFMuS9MhADdi6fAOUkcjm5S4q5YdgyEkGmeHZzvUsy2A0znliDZiSGgFMQJ4RlFZXlDOs5JH+bf7w054i381UgyGXeBAUAfawGHctELqV9vaY2ggeha0V/55frt7Uu5iM1EQZr1MRtKtYJO2noe/lmFApF71qeO6p9siPaam5C0vhHnNbemNLDIVd49H7nWGwwqRqWzgtU6BSh1N41ALlIfhmei4pvJcWmWgcDygnIOjgEfXeGU3rWpd9b0ckkqJxOFxZBZF4OZhwoep7Ue+Zx3pjQ5LZYlplpudYpYVRRbgzXpjV0SX0oITQhDgyoGlp4o71xF6F/od6KBBjgwr2dVkMG+kDUL7iequ66/JWum
  template:
    metadata:
      creationTimestamp: null
      name: azure-keyvault
      namespace: default

