apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: azure-keyvault
  namespace: default
spec:
  encryptedData:
    azurekeyvault.hcl: AgCs65utb29LtFXaS5h9t0tUPpu8l1UxR5XDgf5HJb3c3J8XgWztuYXaQje2NoL7NNGPqm0F9128ppEIpU/RyfNgZ6zwlIZqWMW7YB9OMBODTgiHK2kvzxf/xFsxwcLjj5teADMOQCvRbKDxNkiNWIxTGdD2UqnfzSJ1sb2n2DmK3lnC4q8qLPvK9BO4/9xMY2NX19mrFPwhDzKiwJXXtRFM47EzPU5yzNdnfrDvI1a1cUkhti+2XfJt/Ls0biHs72/KcahEyvcjS23VBrYXE6SLM197IjDAPfDPK3RwgtwfIr9Kq9IsGmPexeR3OCHRXihc+mWLsZyjIbR0aSV+CO1bFJuV+brJHXdE/xJ4DCoEzY3J3PF9j6X40MrIhTpykwYeT5nfWBSoFckcCEDqhjGrUcTHOKPNm+WRzrJeVlB7Lj4tz1tbz/hkno+3pTPrUbZPFDM5baqK9aJgJk0wsSYBAwrTF0tneQAt4lIcytfDJI26tgUbRug5PROLtWMJ/wHamthVMB82iSX5rOOfj55VCcUCmg48Mjvnkd9GnIsTKW3jy/8rVDC7U9TMUDrSUSfYoJVOGjs1zRkhmxJ+nZLMkDmCV8PdRN+HUSrAcm6p+x41jVJhP7sBz1qdHS2HADXfHYAwo6Q7V/Jw3H2+hKLNzPtonEp/pMFbzpgbUKgWobYFk9IiV+3uYqU6DHRkeDvT9VKI+Uu7cTlM4oLIfi6upe5kVgXuPgzcJy4twVWNfULOZAgpshCde17r9DqjU0/O/Xoa8B3aEaO+F1AThd1xULix1Txbqw3n9UmquPQDWNOWngiWuriP4LCT3UM1Hy8kAIWKzX0TTwzL2f6noUfM4yrEitfANIFP26xygLCQJ/30c40LA/ZIthw/AXUPBudR9DxinM14aLw/P2REd/6vEN4IIuO47Xy4cprT9wTB2M1K0ItGCVRXW3MRjaLU9JqFURbkNCcnxJ4etc0pNkB3eZJhbc+KpDRdIsX5CqzyGeZscRL7gnO+zxWLEyOYv6pCP5igeKYO4rGLFSNYw7nOV10zZCnGXHoDmIoh819GDiqK0O3cdozpwQRm7lEgq7wnGJh4Y+dZn/KkcHh2Kp5w34HemtXAiCfVxOtqtLn243aIJL+w79rm1H6q4WTlzfwnVnrkRvd+ihEqymvO4rubQnNjezJ0Qyf08L0A3eELfmRp10QuwmSfC+FwgT4Um8yDKrOwATx9Eyxm/fYE
  template:
    metadata:
      creationTimestamp: null
      name: azure-keyvault
      namespace: default

