apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: azure-keyvault
  namespace: default
spec:
  encryptedData:
    azurekeyvault.hcl: AgAxwzjEHrySSrpSN8L8DDl5ybH1Fp3+KR3YrFYDcB3ozX8YO2JcD7oNA2Xk19ib/ehe2DqYBrmdYVJt9jhSZK8HApty4Q+sveqssp3kcNfQwLSWp7/EqIFLeTm4tWTrQksMGjrSy2lxoT3f3KhTWLe6/kdiNYDryMD8Uoli5Qeh23YMsJ8bHmxM7qTZC+TYFAJj2wrbbNFH4vGWPiglgL7qPXAR/MAf1RTUxG733u8pM5FhsNRdn+RU6cZqVFjXxYJ15ZUbC9jVjw8LxfpN/4OVhiD9JBPBQmuIICroTTPk3VPiheOBNyMsQ+fKNmMI480csObZPCGG+XUymhnLSENFw25LS3BJezSseyQgII3ItD84mcqevN/SkXP+jyO8Y6IuidfdMgw2o5WULFgapKLL9aSec9aDXDjEibuWMlW2Wo5oPVTeJM/bqDJyRPWEDQzBJfPcc++7F5/mBn63WlGRCQ+W8IAoRkePWZ8VPrt4/28Nl/09QL2E66zqSWiSFTK0mtUDCrjojKzSjLJXMDz/lcbMRIrEZfXjyYCPFZtyEdHGz9Pql9/N7SrnNGS6n/+l6wFbjYqYpE+geKU8L/AMREEIjziYRURjlf8inHdNfe10vDW7Yf161I0OFXmo6MAtOxl8P51Sxs5MKk/rvSSqOmPaHL/nPod+0ZKWo5bh8ZueOiGp27q4oRH3fGRuaoFUz7gYnOamccM+QnQX0Ix2VHU+YgM6XBOUgaEixgWyFGEqzIuHte1Vomb4OuGMbowpFlyXEwNkjOYcsnCxovmud2KMU5foT7bZOEIvStBvrDkWDp8sAK4Eup5vwlfCCWVB/8IJLl1d9j0KGN83H/GoGjRvl1Za/hgZAlxD3KOVtlREWNhuxFDPwCZSPg7hx2YRbpMzNxOES/DfYlzq1IQhPq5zZfo1OP0eUOM9os472ZewoENhzB3xB3WsyI8orHqlDv8NSIYAgms0gk0qAfbKWBENRFvsTM9NlVKnk2N4X6Ad9eAJQ+i/uCGOFuyVtU/vng4wcbssfd+d5qH89+TX6FdQTZZpMv0Kw1xc9hsEkL7YzZjN1ftvKVomBNwPzt7B17K9A+R+WGXl8TfN/Y/CgngMcHu4NezWI45d1oQ+E7c/D9ZOdM7na6h/MBf7VynEvtC/yhivTA7LEzz6P7kFk57qw/PVs8H8pukIZpz1uRn7jdw3lxcVPnm0lQ51+53FNoO1s6YPLvmVsGuB
  template:
    metadata:
      creationTimestamp: null
      name: azure-keyvault
      namespace: default

