apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: flux-system
spec:
  chart:
    spec:
      chart: vault
      sourceRef:
        kind: HelmRepository
        name: hashicorp
      version: ">=0.11.0-0"
  values:
    global:
      enabled: true
      tlsDisable: false
    server:
      affinity: ""
      dataStorage:
        enabled: true
        size: 500Mi
      extraEnvironmentVars:
        VAULT_CACERT: /vault/userconfig/vault-server-tls/vault.ca
      extraArgs: -config=/vault/userconfig/azure-keyvault/azurekeyvault.hcl
      extraVolumes:
      - name: vault-server-tls
        type: secret
      - name: azure-keyvault
        type: secret
      ha:
        enabled: true
        raft:
          config: |
            ui = true
            listener "tcp" {
              address = "[::]:8200"
              cluster_address = "[::]:8201"
              tls_cert_file = "/vault/userconfig/vault-server-tls/vault.crt"
              tls_key_file  = "/vault/userconfig/vault-server-tls/vault.key"
              tls_client_ca_file = "/vault/userconfig/vault-server-tls/vault.ca"
            }
            
            storage "raft" {
              path = "/vault/data"
            }
            service_registration "kubernetes" {}
          enabled: true
        replicas: 1
  interval: 1h0m0s
  releaseName: vault
  targetNamespace: default
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
