apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jitsi
  namespace: jitsi
spec:
  releaseName: jitsi
  chart:
    spec:
      chart: ./examples/helm
      sourceRef:
        kind: GitRepository
        name: jitsi
        namespace: flux-system
  interval: 1h0m0s
  values: {}