apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: poc-api
  namespace: flux-system
spec:
  releaseName: poc-api
  targetNamespace: default
  chart:
    spec:
      chart: ./chart
      sourceRef:
        kind: GitRepository
        name: platform-lab-api
        namespace: flux-system
  interval: 1h0m0s
  values:
    component:
      canary:
        enabled: true
        errorRate:
          thresholdRange: 50
        latency:
          thresholdRange: 300000
      serviceAccount: poc-api
      flakiness: 1
      vault:
        role: poc-api
        authSecret: poc/network/api
        redisSecret: poc/persistence/redis