apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: jitsi
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: k8s-helm
  url: https://github.com/Zempashi/docker-jitsi-meet